---
title: "Introdruccion"
author: "Mariella Tognarelli"
date: "10/15/2021"
output: html_document
---
<br>
Hay más tesoros en los libros que en todo el botín del pirata de “La isla de del tesoro” (Walt Disney), pero ¿esos tesoros son variados o simplemente son monedas de oro de distintos tamaños? <br/>
<br>
Sin duda existen billones de libros, unos más populares que otros, que son vendidos a diferentes personas de este mundo, derribando las diferencias del lenguaje y territoriales, pues un libro con autor estadounidense puede ser encontrado en librerías europeas, sudamericanas e incluso asiáticas. Así mismo, al buscar en internet algún libro en específico, lo puede encontrar en tiendas ‘online’ que se encargarán de llevarlo al hogar del comprador independientemente del país en que resida; como es el caso de Book Depository. <br/>
<br>
Este “vendedor” de libros en línea, con sede en el Reino Unido, ofrece un gran catálogo con envío gratuito a al menos 100 países. Lo cual genera una gran interrogante ¿cómo sabe qué libros vender globalmente? ¿Acaso hay alguna especialización de género en sus ventas? ¿hay preferencias de autores? 
Es por este motivo que se analizará una base de datos de esta página de agosto del 2021, para indagar la posible relación existente entre el posicionamiento como Best Seller de la página, con el género del libro y su autor. <br/>
<br>
Para ello se presentará la base de datos con la información de los libros, modificada de tal manera que sólo muestre los primeros 10.000 best seller, pues la base de datos original posee más de un millón de libros registrados. En este mismo sentido, se realizará un cruce de datos entre las bases de datos que contienen las llaves de la base de datos principal. <br/>
<br>
Posteriormente, se analizarán las correlaciones de las variables libro, autor, género, posicionamiento best seller y año de publicación para comenzar el análisis de nuestros datos una vez limpiados. <br/>
<br>
Todo esto con la finalidad de comprobar que el género de un libro está estrechamente relacionado con su posicionamiento best seller. <br/>
